//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DobleCiego.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DobleCiegoEntities : DbContext
    {
        public DobleCiegoEntities()
            : base("name=DobleCiegoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<T_Comentarios> T_Comentarios { get; set; }
        public virtual DbSet<T_Publicaciones> T_Publicaciones { get; set; }
        public virtual DbSet<T_Titulos> T_Titulos { get; set; }
        public virtual DbSet<T_Tracking> T_Tracking { get; set; }
        public virtual DbSet<T_Usuarios> T_Usuarios { get; set; }
    }
}
