//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DobleCiego.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Publicaciones
    {
        public int idPublicacion { get; set; }
        public int idUsuario_Creador { get; set; }
        public string Titulo { get; set; }
        public string imgRef { get; set; }
        public string Descripcion { get; set; }
        public string docRef { get; set; }
        public System.DateTime CreationDate { get; set; }
    }
}
