//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DobleCiego.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Titulos
    {
        public int IdTitulo { get; set; }
        public int idUsuario { get; set; }
        public string Propuesta { get; set; }
        public string ImagenRef { get; set; }
        public string DocRef { get; set; }
        public string Titulo { get; set; }
        public System.DateTime CreationDate { get; set; }
        public string Status { get; set; }
    }
}
