//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DobleCiego.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Tracking
    {
        public int IdTrack { get; set; }
        public int idTitulo { get; set; }
        public Nullable<int> idUsuario_Revisor { get; set; }
        public Nullable<int> idUsuario_Escritor { get; set; }
        public string docRef_Revisor { get; set; }
        public string docRef_Escritor { get; set; }
        public Nullable<System.DateTime> revisorCreateDate { get; set; }
        public Nullable<System.DateTime> escritorCreateDate { get; set; }
    }
}
