//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DobleCiego.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Usuarios
    {
        public int IdUsuario { get; set; }
        public string Nombre { get; set; }
        public string Apellido { get; set; }
        public string Sexo { get; set; }
        public System.DateTime FechaNac { get; set; }
        public string Password { get; set; }
        public string Telefono { get; set; }
        public string Rol { get; set; }
        public string Status { get; set; }
        public string Correo { get; set; }
    }
}
